name: APIsec Scan

on:
  push:
    branches: [ main ]
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  apisec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run APIsec scan
        uses: apisec-ai/apisec-scan@latest
        with:
          apisec_token: ${{ secrets.APISEC_TOKEN }}
